### ISSUE TITLE
Container status: "unhealthy" since your commits yesterday

### ISSUE THREAD

**Issue by kj187** [spryker/docker-chromedriver#4]
We use the docker/sdk. Within the "testing" commands the "chromedriver" is used. Since yesterday we get the following errors which blocks us. Unfortunately the chromedriver images does not have tags, just a latest branch. So you are able to block our pipelines at any point of time ;( 

```
$ docker/sdk testing codecept run -vvv -c codeception.functional.yml --xml /data/$JUNITREPORT
Warning: Neither SSH agent or COMPOSER_AUTH is configured. Private repositories would not be accessible. 
spryker_ci_cli_ssh_relay_1 is up-to-date
spryker_ci_cli_1 is up-to-date
Could not wait for spryker_ci_webdriver_1 anymore. Container status: "unhealthy"
```

```
$ docker/sdk testing console queue:worker:start --stop-when-empty
Warning: Neither SSH agent or COMPOSER_AUTH is configured. Private repositories would not be accessible. 
spryker_ci_cli_ssh_relay_1 is up-to-date
spryker_ci_cli_1 is up-to-date
Could not wait for spryker_ci_webdriver_1 anymore. Container status: "unhealthy"
```

**Comment by alexanderM91** [comment]
Hey @kj187, please update the docker/sdk to the latest version. Thank you.

**Comment by kj187** [comment]
I will do that, thanks. 
But is it still possible that you use tags for the image and use that tag in docker-compose in the docker/sdk?
Then its in our hand when wo do an update, now we are blocked and forced to make a docker/sdk update.
